import * as S from './styles'

export function HeroImg() {
  return (
    <S.Container>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 235 117"
        role="img"
        aria-label="an illustration of a girl with the NextJS logo on her right side"
      >
        <defs>
          <filter
            id="dl"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="dk"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="dj"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="di"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="dh"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="dg"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="df"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="de"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="dd"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="dc"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="db"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="da"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cZ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cY"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cX"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cW"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cV"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cU"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cT"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cS"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cR"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cQ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cP"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cO"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cN"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cM"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cL"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cK"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cJ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cI"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cH"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cG"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cF"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cE"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cD"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cC"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cB"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cA"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cz"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cy"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cx"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cw"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cv"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cu"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ct"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cs"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cr"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cq"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cp"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="co"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cn"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cm"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cl"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ck"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cj"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ci"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ch"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cg"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cf"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ce"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cd"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cc"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="cb"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ca"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bZ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bY"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bX"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bW"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bV"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bU"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bT"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bS"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bR"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bQ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bP"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bO"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bN"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bM"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bL"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bK"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bJ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bI"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bH"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bG"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bF"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bE"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bD"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bC"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bB"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bA"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bz"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="by"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bx"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bw"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bv"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bu"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bt"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bs"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="br"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bq"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bp"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bo"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bn"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bm"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bl"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bk"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bj"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bi"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bh"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bg"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bf"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="be"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bd"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bc"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="bb"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ba"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aZ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aY"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aX"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aW"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aV"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aU"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aT"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aS"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aR"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aQ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aP"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aO"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aN"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aM"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aL"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aK"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aJ"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aI"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aH"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aG"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aF"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aE"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aD"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aC"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aB"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aA"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="az"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ay"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ax"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aw"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="av"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="au"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="at"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="as"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ar"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aq"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ap"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ao"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="an"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="am"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="al"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ak"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aj"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ai"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ah"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ag"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="af"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ae"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ad"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ac"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="ab"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="aa"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="Z"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="Y"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="X"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="W"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="V"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="U"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="T"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="S"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="R"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="Q"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="P"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="O"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="N"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="M"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="L"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="K"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="J"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="I"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="H"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="G"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="F"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="E"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="D"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="C"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="B"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="A"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="z"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="y"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="x"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="w"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="v"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="u"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="t"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="s"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="r"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="q"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="p"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="o"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="n"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="m"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="l"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="k"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="j"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="i"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="h"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="g"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="f"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="e"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="d"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="c"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="b"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
          <filter
            id="a"
            width="3.8"
            height="3.8"
            x="-1"
            y="-1"
            colorInterpolationFilters="sRGB"
          >
            <feGaussianBlur stdDeviation="6.5" />
          </filter>
        </defs>
        <g transform="scale(.26458)">
          <circle cx="190" cy="79.9" r="5.5" fill="#e0e0e0" filter="url(#a)" />
          <circle
            cx="218.1"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#b)"
          />
          <circle
            cx="246.2"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#c)"
          />
          <circle
            cx="274.3"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#d)"
          />
          <circle
            cx="302.4"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#e)"
          />
          <circle
            cx="330.5"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#f)"
          />
          <circle
            cx="358.6"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#g)"
          />
          <circle
            cx="386.7"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#h)"
          />
          <circle
            cx="414.7"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#i)"
          />
          <circle
            cx="442.8"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#j)"
          />
          <circle
            cx="470.9"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#k)"
          />
          <circle cx="499" cy="79.9" r="5.5" fill="#e0e0e0" filter="url(#l)" />
          <circle
            cx="527.1"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#m)"
          />
          <circle
            cx="555.2"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#n)"
          />
          <circle
            cx="583.3"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#o)"
          />
          <circle
            cx="611.4"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#p)"
          />
          <circle
            cx="639.5"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#q)"
          />
          <circle
            cx="667.6"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#r)"
          />
          <circle
            cx="695.7"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#s)"
          />
          <circle
            cx="723.8"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#t)"
          />
          <circle
            cx="751.9"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#u)"
          />
          <circle
            cx="779.9"
            cy="79.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#v)"
          />
          <circle cx="190" cy="108.3" r="5.5" fill="#e0e0e0" filter="url(#w)" />
          <circle
            cx="218.1"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#x)"
          />
          <circle
            cx="246.2"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#y)"
          />
          <circle
            cx="274.3"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#z)"
          />
          <circle
            cx="302.4"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#A)"
          />
          <circle
            cx="330.5"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#B)"
          />
          <circle
            cx="358.6"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#C)"
          />
          <circle
            cx="386.7"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#D)"
          />
          <circle
            cx="414.7"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#E)"
          />
          <circle
            cx="442.8"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#F)"
          />
          <circle
            cx="470.9"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#G)"
          />
          <circle cx="499" cy="108.3" r="5.5" fill="#e0e0e0" filter="url(#H)" />
          <circle
            cx="527.1"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#I)"
          />
          <circle
            cx="555.2"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#J)"
          />
          <circle
            cx="583.3"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#K)"
          />
          <circle
            cx="611.4"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#L)"
          />
          <circle
            cx="639.5"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#M)"
          />
          <circle
            cx="667.6"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#N)"
          />
          <circle
            cx="695.7"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#O)"
          />
          <circle
            cx="723.8"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#P)"
          />
          <circle
            cx="751.9"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#Q)"
          />
          <circle
            cx="779.9"
            cy="108.3"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#R)"
          />
          <circle cx="190" cy="136.8" r="5.5" fill="#e0e0e0" filter="url(#S)" />
          <circle
            cx="218.1"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#T)"
          />
          <circle
            cx="246.2"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#U)"
          />
          <circle
            cx="274.3"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#V)"
          />
          <circle
            cx="302.4"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#W)"
          />
          <circle
            cx="330.5"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#X)"
          />
          <circle
            cx="358.6"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#Y)"
          />
          <circle
            cx="386.7"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#Z)"
          />
          <circle
            cx="414.7"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aa)"
          />
          <circle
            cx="442.8"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ab)"
          />
          <circle
            cx="470.9"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ac)"
          />
          <circle
            cx="499"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ad)"
          />
          <circle
            cx="527.1"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ae)"
          />
          <circle
            cx="555.2"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#af)"
          />
          <circle
            cx="583.3"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ag)"
          />
          <circle
            cx="611.4"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ah)"
          />
          <circle
            cx="639.5"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ai)"
          />
          <circle
            cx="667.6"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aj)"
          />
          <circle
            cx="695.7"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ak)"
          />
          <circle
            cx="723.8"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#al)"
          />
          <circle
            cx="751.9"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#am)"
          />
          <circle
            cx="779.9"
            cy="136.8"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#an)"
          />
          <circle
            cx="190"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ao)"
          />
          <circle
            cx="218.1"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ap)"
          />
          <circle
            cx="246.2"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aq)"
          />
          <circle
            cx="274.3"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ar)"
          />
          <circle
            cx="302.4"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#as)"
          />
          <circle
            cx="330.5"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#at)"
          />
          <circle
            cx="358.6"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#au)"
          />
          <circle
            cx="386.7"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#av)"
          />
          <circle
            cx="414.7"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aw)"
          />
          <circle
            cx="442.8"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ax)"
          />
          <circle
            cx="470.9"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ay)"
          />
          <circle
            cx="499"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#az)"
          />
          <circle
            cx="527.1"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aA)"
          />
          <circle
            cx="555.2"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aB)"
          />
          <circle
            cx="583.3"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aC)"
          />
          <circle
            cx="611.4"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aD)"
          />
          <circle
            cx="639.5"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aE)"
          />
          <circle
            cx="667.6"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aF)"
          />
          <circle
            cx="695.7"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aG)"
          />
          <circle
            cx="723.8"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aH)"
          />
          <circle
            cx="751.9"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aI)"
          />
          <circle
            cx="779.9"
            cy="165.2"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aJ)"
          />
          <circle
            cx="190"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aK)"
          />
          <circle
            cx="218.1"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aL)"
          />
          <circle
            cx="246.2"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aM)"
          />
          <circle
            cx="274.3"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aN)"
          />
          <circle
            cx="302.4"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aO)"
          />
          <circle
            cx="330.5"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aP)"
          />
          <circle
            cx="358.6"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aQ)"
          />
          <circle
            cx="386.7"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aR)"
          />
          <circle
            cx="414.7"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aS)"
          />
          <circle
            cx="442.8"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aT)"
          />
          <circle
            cx="470.9"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aU)"
          />
          <circle
            cx="499"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aV)"
          />
          <circle
            cx="527.1"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aW)"
          />
          <circle
            cx="555.2"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aX)"
          />
          <circle
            cx="583.3"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aY)"
          />
          <circle
            cx="611.4"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#aZ)"
          />
          <circle
            cx="639.5"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ba)"
          />
          <circle
            cx="667.6"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bb)"
          />
          <circle
            cx="695.7"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bc)"
          />
          <circle
            cx="723.8"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bd)"
          />
          <circle
            cx="751.9"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#be)"
          />
          <circle
            cx="779.9"
            cy="193.7"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bf)"
          />
          <circle
            cx="190"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bg)"
          />
          <circle
            cx="218.1"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bh)"
          />
          <circle
            cx="246.2"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bi)"
          />
          <circle
            cx="274.3"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bj)"
          />
          <circle
            cx="302.4"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bk)"
          />
          <circle
            cx="330.5"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bl)"
          />
          <circle
            cx="358.6"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bm)"
          />
          <circle
            cx="386.7"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bn)"
          />
          <circle
            cx="414.7"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bo)"
          />
          <circle
            cx="442.8"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bp)"
          />
          <circle
            cx="470.9"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bq)"
          />
          <circle
            cx="499"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#br)"
          />
          <circle
            cx="527.1"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bs)"
          />
          <circle
            cx="555.2"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bt)"
          />
          <circle
            cx="583.3"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bu)"
          />
          <circle
            cx="611.4"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bv)"
          />
          <circle
            cx="639.5"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bw)"
          />
          <circle
            cx="667.6"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bx)"
          />
          <circle
            cx="695.7"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#by)"
          />
          <circle
            cx="723.8"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bz)"
          />
          <circle
            cx="751.9"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bA)"
          />
          <circle
            cx="779.9"
            cy="222.1"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bB)"
          />
          <circle
            cx="190"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bC)"
          />
          <circle
            cx="218.1"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bD)"
          />
          <circle
            cx="246.2"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bE)"
          />
          <circle
            cx="274.3"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bF)"
          />
          <circle
            cx="302.4"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bG)"
          />
          <circle
            cx="330.5"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bH)"
          />
          <circle
            cx="358.6"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bI)"
          />
          <circle
            cx="386.7"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bJ)"
          />
          <circle
            cx="414.7"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bK)"
          />
          <circle
            cx="442.8"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bL)"
          />
          <circle
            cx="470.9"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bM)"
          />
          <circle
            cx="499"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bN)"
          />
          <circle
            cx="527.1"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bO)"
          />
          <circle
            cx="555.2"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bP)"
          />
          <circle
            cx="583.3"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bQ)"
          />
          <circle
            cx="611.4"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bR)"
          />
          <circle
            cx="639.5"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bS)"
          />
          <circle
            cx="667.6"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bT)"
          />
          <circle
            cx="695.7"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bU)"
          />
          <circle
            cx="723.8"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bV)"
          />
          <circle
            cx="751.9"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bW)"
          />
          <circle
            cx="779.9"
            cy="250.6"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bX)"
          />
          <circle cx="190" cy="279" r="5.5" fill="#e0e0e0" filter="url(#bY)" />
          <circle
            cx="218.1"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#bZ)"
          />
          <circle
            cx="246.2"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ca)"
          />
          <circle
            cx="274.3"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cb)"
          />
          <circle
            cx="302.4"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cc)"
          />
          <circle
            cx="330.5"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cd)"
          />
          <circle
            cx="358.6"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ce)"
          />
          <circle
            cx="386.7"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cf)"
          />
          <circle
            cx="414.7"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cg)"
          />
          <circle
            cx="442.8"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ch)"
          />
          <circle
            cx="470.9"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ci)"
          />
          <circle cx="499" cy="279" r="5.5" fill="#e0e0e0" filter="url(#cj)" />
          <circle
            cx="527.1"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ck)"
          />
          <circle
            cx="555.2"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cl)"
          />
          <circle
            cx="583.3"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cm)"
          />
          <circle
            cx="611.4"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cn)"
          />
          <circle
            cx="639.5"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#co)"
          />
          <circle
            cx="667.6"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cp)"
          />
          <circle
            cx="695.7"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cq)"
          />
          <circle
            cx="723.8"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cr)"
          />
          <circle
            cx="751.9"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cs)"
          />
          <circle
            cx="779.9"
            cy="279"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#ct)"
          />
          <circle
            cx="190"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cu)"
          />
          <circle
            cx="218.1"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cv)"
          />
          <circle
            cx="246.2"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cw)"
          />
          <circle
            cx="274.3"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cx)"
          />
          <circle
            cx="302.4"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cy)"
          />
          <circle
            cx="330.5"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cz)"
          />
          <circle
            cx="358.6"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cA)"
          />
          <circle
            cx="386.7"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cB)"
          />
          <circle
            cx="414.7"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cC)"
          />
          <circle
            cx="442.8"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cD)"
          />
          <circle
            cx="470.9"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cE)"
          />
          <circle
            cx="499"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cF)"
          />
          <circle
            cx="527.1"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cG)"
          />
          <circle
            cx="555.2"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cH)"
          />
          <circle
            cx="583.3"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cI)"
          />
          <circle
            cx="611.4"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cJ)"
          />
          <circle
            cx="639.5"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cK)"
          />
          <circle
            cx="667.6"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cL)"
          />
          <circle
            cx="695.7"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cM)"
          />
          <circle
            cx="723.8"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cN)"
          />
          <circle
            cx="751.9"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cO)"
          />
          <circle
            cx="779.9"
            cy="307.5"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cP)"
          />
          <circle
            cx="190"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cQ)"
          />
          <circle
            cx="218.1"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cR)"
          />
          <circle
            cx="246.2"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cS)"
          />
          <circle
            cx="274.3"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cT)"
          />
          <circle
            cx="302.4"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cU)"
          />
          <circle
            cx="330.5"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cV)"
          />
          <circle
            cx="358.6"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cW)"
          />
          <circle
            cx="386.7"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cX)"
          />
          <circle
            cx="414.7"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cY)"
          />
          <circle
            cx="442.8"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#cZ)"
          />
          <circle
            cx="470.9"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#da)"
          />
          <circle
            cx="499"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#db)"
          />
          <circle
            cx="527.1"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dc)"
          />
          <circle
            cx="555.2"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dd)"
          />
          <circle
            cx="583.3"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#de)"
          />
          <circle
            cx="611.4"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#df)"
          />
          <circle
            cx="639.5"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dg)"
          />
          <circle
            cx="667.6"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dh)"
          />
          <circle
            cx="695.7"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#di)"
          />
          <circle
            cx="723.8"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dj)"
          />
          <circle
            cx="751.9"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dk)"
          />
          <circle
            cx="779.9"
            cy="335.9"
            r="5.5"
            fill="#e0e0e0"
            filter="url(#dl)"
          />
          <path fill="#1de9b6" d="M0 341h888v2H0z" />
          <circle cx="857.4" cy="271.9" r="28.9" fill="#c2185b" />
          <circle cx="869.4" cy="309.4" r="3.7" fill="#1de9b6" />
          <path
            fill="#2962ff"
            d="M328 170h115v9H338v69h99v9h-99v76h106v9H328zm125 0h12l55 75 55-75 75-96-123 179 63 89h-12l-58-81-59 81h-12l64-89Zm142 9v-9h131v9h-60v163h-11V179Zm-412-9h14l182 272-76-100-109-159v159h-11zm542 160a4 4 0 1 1 4-4 4 4 0 0 1-4 4zm11-10h5c0 3 3 5 6 5s6-2 6-6v-27h5v27c0 7-4 11-11 11s-11-4-11-10zm30-1h6c0 4 3 6 8 6s8-2 8-5-2-5-7-6l-4-1c-7-2-10-5-10-11s5-11 13-11 13 5 14 11h-6c0-3-3-6-8-6-4 0-7 3-7 6s2 4 6 5l5 1c7 2 10 5 10 11 0 7-5 11-14 11-8 0-14-4-14-11z"
          />
          <circle cx="119.9" cy="63.4" r="10.8" fill="#c2185b" />
          <path
            fill="#c2185b"
            d="M123 53a11 11 0 0 1 9 16 11 11 0 1 0-18-12 11 11 0 0 1 9-4z"
          />
          <circle cx="99.7" cy="31.7" r="31.7" fill="#c2185b" />
          <path
            fill="#c2185b"
            d="M75 12a32 32 0 0 1 44-3l-1-1a32 32 0 0 0-42 47l1 1a32 32 0 0 1-2-44z"
          />
          <path
            fill="#fbbebe"
            d="m130 112 5 28 6 54s1 22-6 23-6-24-6-24l-8-47-3-28Z"
          />
          <circle cx="100.2" cy="38.5" r="19.5" fill="#fbbebe" />
          <path
            fill="#fbbebe"
            d="m85 47-3 18 21 5V52zM34 319l-2 17h10l5-13zm76 3 2 13h11v-12z"
          />
          <path
            fill="#424242"
            d="m117 140-53 8-4 38-6 55-24 81 24 2 42-108 11 109h24l2-111s1-62-12-66zM44 334l-14-3-5 28s-11 37 3 34 11-34 11-34zm66 0 14-3 5 28s11 37-3 34-11-34-11-34z"
          />
          <path fill="#fbbebe" d="M43 100s-7 34-4 42l22 37 6-12-16-32 5-32z" />
          <path
            fill="#424242"
            d="m107 77-2-13s-20-3-23-9l-6 10-19 4s-10 0-11 8l-6 25 15 5 11 42 49-7-3-22 3-6 2 6 16-3s1-29-15-34z"
          />
          <path fill="#c2185b" d="m112 31 2 7h3V17H82v21h5l6-7-1 7h21z" />
          <path fill="#1de9b6" d="m856 343 1-71 2 71z" />
          <path fill="#1de9b6" d="m857 333 14-26-13 27z" />
        </g>
      </svg>
    </S.Container>
  )
}
